### ISSUE TITLE
initialScrollToIndex does not work when input data size is reduced

### ISSUE THREAD

**Issue by Rahulzz** [rdhox/react-native-smooth-picker#14]
Following code works fine
```
const petTypes = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

export default class Example extends Component {
  constructor(props) {
    super(props);
    this.state = {
      selected: 5
    };
  }

  onPetChange = index => {
    this.setState({
        selected: index
    });
  };

  render() {
    return (
      <SmoothPicker
        style={{ marginTop: 300 }}
        horizontal
        initialScrollToIndex={this.state.selected}
        keyExtractor={(_, index) => index.toString()}
        ref={ref => (this.refPetList = ref)}
        showsHorizontalScrollIndicator={false}
        bounces={true}
        magnet={true}
        scrollAnimation
        data={petTypes}
        onSelected={({ item, index }) => this.onPetChange(index)}
        renderItem={({ item, index }) => {
          return this.petPickerItem(index, item);
        }}
      />
    );
  }

  petPickerItem = (index, item) => {
    return <Text style={this.state.selected === index?{color:"red"}:{color: "#000000"}}>{index}</Text>;
  };
}
```

Result for the above code
<img width="471" alt="Screen Shot 2019-08-30 at 2 35 04 AM" src="https://user-images.githubusercontent.com/20224717/63976405-e1b01d80-cace-11e9-89e1-76efbe3b82b9.png">

When the input array is reduced by one value to the following
`const petTypes = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];`

Following is the result
<img width="456" alt="Screen Shot 2019-08-30 at 2 37 15 AM" src="https://user-images.githubusercontent.com/20224717/63976531-26d44f80-cacf-11e9-81ff-703e9cedf309.png">

**Comment by rdhox** [comment]
Hey!
I don't really understand how your screenshot are linked to the initialScrollToIndex, but there is an issue on the react-native repo about the "scrollTo" method that doesn't work (I have the same issue right now on a project):

https://github.com/facebook/react-native/issues/24531

**Comment by Rahulzz** [comment]
The item matching scrollToIndex should appear in the middle of the screen. When the array consists of 11 elements, the list scrolls and brings item 5 to the middle. Whereas, when the array contains 10 elements the initial scroll doesn't work which positions the list to the left of the screen.

This snippet used was to test the functionality with a basic code. The actual functionality I am developing has just three items and initial scroll doesn't work.

Following is what I currently have
<img width="468" alt="Screen Shot 2019-08-30 at 3 47 42 PM" src="https://user-images.githubusercontent.com/20224717/64013502-92ed9c80-cb3d-11e9-8e8d-a7632eda6269.png">

Following is what is expected
<img width="507" alt="Screen Shot 2019-08-30 at 3 48 41 PM" src="https://user-images.githubusercontent.com/20224717/64013549-ab5db700-cb3d-11e9-8104-8d264950966c.png">

**Comment by Brianop** [comment]
Did you find a workaround for this ?

**Comment by Rahulzz** [comment]
Nope, I haven't. I actually quit working on that project. I am sorry.

**Comment by xuandac** [comment]
Did you find a workaround for this ?. I really need it

**Comment by pmkemper** [comment]
I have found the same issue: initialScrollToIndex does not work when the data consists of fewer than 11 items.

**Comment by bananemo** [comment]
I encountered the same issue too, did anyone find a workaround for this?
