### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by eldareini** [rdhox/react-native-smooth-picker#18]
Hi, 
It seems that there is no rtl support. when I try to use the component on rtl the direction of the scroll is the opposite direction from the chosen index. like if I scroll left the chosen one scroll right. 
if this could be fixed, it will be great!

**Comment by rdhox** [comment]
Hey!
Apparently there is no support for rtl on react-native Flatlist component:
https://github.com/facebook/react-native/issues/19150

The issue is still open. maybe this solution can temporarily do the tricks for you:
https://github.com/facebook/react-native/issues/19150#issuecomment-574110469

**Comment by eldareini** [comment]
Hey,
Unfortunately, that doesn't help. the problem in RTL is only in android, in ios everything works great.

**Comment by rdhox** [comment]
Sorry. Since I use Flatlist, I can't do much here. 
Follow the react-native issue on this and hopefully it will be done soon!
