### ISSUE TITLE
enable using external scrolltoindex to select item

### ISSUE THREAD

**Issue by boaz-lachman** [rdhox/react-native-smooth-picker#19]
Hi,

The component looks excellent and very unusable.

I have a minor request.

I want to also enable picking an item by pressing the item itself.

Now, due to the ref feature in this component, I can use "scrollToIndex" to achieve the aforementioned goal. However, this choice does not affect the internal state of the smooth picker component and thus, when performing the scrollToIndex, the selection does not change.

My request is could you please add a prop which on change changes the selected item/index or could you please a "scrollToIndex" method that can allow to programmatically scroll to the item and perform the internal state change?

**Comment by rdhox** [comment]
Hi,

I don't really understand your problem here. Can you show me some code ?
Thanks!

**Comment by boaz-lachman** [comment]
Hi,

Thank you for the quick response.

For example the item renderer is : 

 const itemRenderer = (item: string, index: number) : JSX.Element => {
        return (
            <View
                style={styles.itemContainer}>
                <TouchableOpacity 
                style={styles.touchableContainer}
                onPress={() => {
                    setSelectedIndex(index);
                    //reference to flatlist in smooth picker
                    pickerRef.current.scrollToIndex({animated: true, viewOffset: -30, index: index})
                    
                }}
                >
                     <Text 
                         style={{fontSize: 16}}>
                         {item}
                     </Text>
                </TouchableOpacity>
            </View>
        )
    },

While the scrolling does work, it does not affect the selected item in the smoothpicker component, since it is not initiated by a drag with momentum.

Thank you

**Comment by rdhox** [comment]
The motivation behind this library is to create a picker, which by definition means that you scroll a list of items and one of the item is automatically selected from its position on the screen. 
If you want a "normal" list of item that can be selected by manual selection, why just not using a Flatlist or SectionList components of react-native?

**Comment by boaz-lachman** [comment]
Hi,

Because what I require is both picking through motion and pick through press, combining the 2 sensibilities.

**Comment by rdhox** [comment]
Ok, well I guess you can try doing something like that:

https://snack.expo.io/@rdhox/smoothpicker-two-selector

It is working, even if it was not design to be used like that. I'll see if I have the time to make this behavior as an option in the future!

**Comment by boaz-lachman** [comment]
Thank you very much :)

**Comment by rdhox** [comment]
I updated the component with the new feature. You can check the readme to use the new props.

**Comment by boaz-lachman** [comment]
Thank you very much that is excatly what I needed

**Comment by rdhox** [comment]
Feature is available in the 1.1.2 version.
