### ISSUE TITLE
Inverted list problem

### ISSUE THREAD

**Issue by jullk** [rdhox/react-native-smooth-picker#23]
Hi,
I’m having a problem with a horizontal inverted list - initially, all is rendered fine (active option not centered, though) but after a first scroll, the first item looks pulled to the very end of the view.

I would appreciate any help.

Platforms: iOS, Android
react-native-smooth-picker: 1.1.3

https://snack.expo.io/@jullk/horizontal-inverted-list
https://monosnap.com/file/d6IgwxKwj3YTDwcIo2ZxHggA1FUEFC

**Comment by rdhox** [comment]
The library not really work with the inverted option because of the automatic margin calculated. 
One of the trick is to define negative margin:

```js
      <SmoothPicker
        initialScrollToIndex={selected}
        keyExtractor={(_, index) => index.toString()}
        scrollAnimation
        showsHorizontalScrollIndicator={false}
        data={dataCity}
        onSelected={({ item, index }) => handleChange(index)}
        renderItem={option => ItemToRender(option, selected)}
        magnet
        horizontal
        inverted
        startMargin={-10}
        endMargin={-10}
      />
```

But it makes the alignment of the select items not working. The most easy workaround, is too reverse the array and not use the inverted option of the VirtualizedList:

```js
      <SmoothPicker
        initialScrollToIndex={selected}
        keyExtractor={(_, index) => index.toString()}
        scrollAnimation
        showsHorizontalScrollIndicator={false}
        data={dataCity.slice().reverse()}
        onSelected={({ item, index }) => handleChange(index)}
        renderItem={option => ItemToRender(option, selected)}
        magnet
        horizontal
      />
```

**Comment by jullk** [comment]
ok, got it, thanks anyway!
