### ISSUE TITLE
Use custom FlatList component

### ISSUE THREAD

**Issue by jerearaujo03** [rdhox/react-native-smooth-picker#25]
I need to use FlatList from `react-native-gesture-handler` for being able to scroll on nested component.

Maybe could be something like this:
```
import { FlatList } from 'react-native-gesture-handler';

<SmoothPicker
  ...
  flatListComponent={<FlatList />}
/>

**Comment by rdhox** [comment]
It's not really common demand. If you're ok to make a PR with this option, why not. Otherwise you can easily fork the repo and import the flatlist from your library of choice.

**Comment by jerearaujo03** [comment]
#27
