### ISSUE TITLE
Regular React Support

### ISSUE THREAD

**Issue by exoRift** [rdhox/react-native-smooth-picker#30]
When I try to use this component with regular React, I get an error that it's using experimental features. Would it be possible to either not use the experiment features or make another version that's compatible with normal React?

**Comment by rdhox** [comment]
What do you mean by regular React?

**Comment by exoRift** [comment]
It uses experimental features that are a part of React Native and not React. I looked at the code and it seems to be mostly syntactic so I was wondering if you could change it to traditional syntax.

**Comment by rdhox** [comment]
Yes this library is for React Native, it will not work if you use it for React only. There is no experimental features at all.
