### ISSUE TITLE
Export interface SmoothPickerProps

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [rdhox/react-native-smooth-picker#35]
Hello, thanks for this amazing lib!!

I am building an custom date picker from this smooth picker, and it would be a great help if the interface props from SmoothPicker were exported.  I would like to create a PR for it.

**Comment by rdhox** [comment]
Merged and updated on npm, v1.1.5.

Sorry for the delay!

**Comment by PedroAugustoRamalhoDuarte** [comment]
No problem, thanks for the update!!
