### ISSUE TITLE
initialScrollToIndex is not working correctly

### ISSUE THREAD

**Issue by paul019** [rdhox/react-native-smooth-picker#9]
I've tried to use the prop `initialScrollToIndex` to make the picker select its first item when it is rendered. So I used the following code:

```
<SmoothPicker
  offsetSelection={0}
  horizontal={true}
  snapInterval={50}
  showsHorizontalScrollIndicator={false}
  initialScrollToIndex={0}

  data={data.map((item, index) => item.text)}
  onSelected={({item, index}) => this.handleChangeSelectedItem(index)}
  renderItem={({item, index}) => (
    <Text
      style={index===this.state.selectedIndex ? stylestext_selected : styles.text}
      key={item}
    >
      {item}
    </Text>
  )}

  magnet={true}
  scrollAnimation={true}
  snapToAlignment={'start'}
/>
```

Unfortunately, no item in the list is selected, when its rendered first:

<img width="355" alt="bildschirmfoto 2019-01-25 um 13 49 20" src="https://user-images.githubusercontent.com/39464035/51747076-a5d05800-20a8-11e9-83d2-51eae70b511e.png">

Did I make a mistake when using the prop?

**Comment by rdhox** [comment]
Which value you give to the state `selectedIndex` when the component is mount?
If you don't give `selectedIndex` the default value that is the same of the initial index that you want selected, the condition `index===this.state.selectedIndex`will be false, so the selected style will not be applied.
Check if it's your problem, if not we will look deeper ;)

**Comment by paul019** [comment]
Thanks for the answer. This was in fact my problem, but changing `this.state.selectedIndex` to 0 before the component mounts, was not the full solution to my issue:

Now the option "Jetzt" is highlighted in the beginning, but it is still on the left, when the component first mounts, although I specified `snapToAlignment={'center'}`. When I now try to swipe to the left, there is an annoying skip of the items in the picker to the right, so that the first option ("Jetzt") is in the center. What's the problem here?

**Comment by rdhox** [comment]
I don't really understand the behavior that you describe. `snapToAlignement`is actually a prop that come from the ScrollView parent, you can find more about it here: 

https://facebook.github.io/react-native/docs/scrollview#snaptoalignment

All your items in your list have the same width? 
You also can't use snapInterval and magnet props simultaneously like it is mentioned in the doc.

**Comment by Rahulzz** [comment]
This issue still exists. 

Following code works fine
`const petTypes = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

export default class Example extends Component {
  constructor(props) {
    super(props);
    this.state = {
      selected: 5
    };
  }

  onPetChange = index => {
    this.setState({
        selected: index
    });
  };

  render() {
    return (
      <SmoothPicker
        style={{ marginTop: 300 }}
        horizontal
        initialScrollToIndex={this.state.selected}
        keyExtractor={(_, index) => index.toString()}
        ref={ref => (this.refPetList = ref)}
        showsHorizontalScrollIndicator={false}
        bounces={true}
        magnet={true}
        scrollAnimation
        data={petTypes}
        onSelected={({ item, index }) => this.onPetChange(index)}
        renderItem={({ item, index }) => {
          return this.petPickerItem(index, item);
        }}
      />
    );
  }

  petPickerItem = (index, item) => {
    return <Text style={this.state.selected === index?{color:"red"}:{color: "#000000"}}>{index}</Text>;
  };
}
`

Result for the above code
<img width="471" alt="Screen Shot 2019-08-30 at 2 35 04 AM" src="https://user-images.githubusercontent.com/20224717/63976405-e1b01d80-cace-11e9-89e1-76efbe3b82b9.png">

When the input array is reduced by one value to the following
`const petTypes = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];`

Following is the result
<img width="456" alt="Screen Shot 2019-08-30 at 2 37 15 AM" src="https://user-images.githubusercontent.com/20224717/63976531-26d44f80-cacf-11e9-81ff-703e9cedf309.png">
